# Generated by Django 5.2 on 2025-07-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='categories/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(upload_to='catalog/'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.category'),
        ),
    ]
