# Generated by Django 5.2 on 2025-07-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
