# Generated by Django 5.2 on 2025-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_contact_email_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
