# Generated by Django 5.2 on 2025-07-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='price_from',
        ),
    ]
